steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}', '-f', '${_DOCKERFILE}', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']
    
  # Deploy container image to Cloud Run with environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - '${_ENV_VARS}'
    
# Substitution variables with default values
substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/skillmetricspro-fixed:latest'
  _DOCKERFILE: 'Dockerfile.cloud-run-fixed'
  _SERVICE_NAME: 'skillmetrics'
  _REGION: 'us-central1'
  _ENV_VARS: >-
    NODE_ENV=production,
    CLOUD_SQL_CONNECTION_NAME=your-project:region:instance,
    CLOUD_SQL_USER=db_user,
    CLOUD_SQL_PASSWORD=db_password,
    CLOUD_SQL_DATABASE=db_name,
    PGUSER=db_user,
    PGPASSWORD=db_password,
    PGDATABASE=db_name

# Store images in Google Container Registry
images:
  - '${_IMAGE_NAME}'
  
# Set a timeout for the build
timeout: '1800s'
