steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/imposing-elixir-440911-u9/skills-management-app:latest', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/imposing-elixir-440911-u9/skills-management-app:latest']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'skills-management-app'
  - '--image'
  - 'gcr.io/imposing-elixir-440911-u9/skills-management-app:latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--service-account'
  - 'skillmetrics-service-account@imposing-elixir-440911-u9.iam.gserviceaccount.com'
  - '--update-env-vars'
  - 'NODE_ENV=production,PORT=8080,HOST=0.0.0.0,SESSION_SECRET=${_SESSION_SECRET}'

images:
- 'gcr.io/imposing-elixir-440911-u9/skills-management-app:latest'

substitutions:
  _SESSION_SECRET: 'generated-secure-session-secret'

options:
  logging: CLOUD_LOGGING_ONLY
