steps:
# Build Docker image with optimized configuration
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/skillmetricspro7:latest', '-f', 'Dockerfile.cloudrun', '.']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'skills-management-app'
  - '--image'
  - 'gcr.io/${PROJECT_ID}/skillmetricspro7:latest'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--service-account'
  - 'skillmetrics-service-account@imposing-elixir-440911-u9.iam.gserviceaccount.com'
  - '--update-env-vars'
  - 'NODE_ENV=production,HOST=0.0.0.0,PORT=8080,SESSION_SECRET=${_SESSION_SECRET}'
  - '--memory'
  - '1Gi'
  - '--min-instances'
  - '0'
  - '--max-instances'
  - '10'
  - '--timeout'
  - '300s'
  - '--set-cloudsql-instances'
  - '${_CLOUD_SQL_CONNECTION_NAME}'

images:
- 'gcr.io/${PROJECT_ID}/skillmetricspro7:latest'

substitutions:
  _SESSION_SECRET: "generated-session-secret-for-production-environment"
  _CLOUD_SQL_CONNECTION_NAME: "imposing-elixir-440911-u9:us-central1:skills-db"

options:
  logging: CLOUD_LOGGING_ONLY
